### ISSUE TITLE
newer mindreader doesn't use `mindreader-node-oneblock-suffix`

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/merger#11]
mindreader-node-oneblock-suffix parameter seems to be ignored in the newest mindreader.

Filenames are like `0006520353-20220311T210830.0-9749865e-8e377af4-6520153-generated.dbin.zst`

**Comment by sduchesneau** [comment]
Fixed here: https://github.com/streamingfast/node-manager/commit/1f14183a6ccd43570a8f2f63bcaba728446e5549

**Comment by matthewdarwin** [comment]
Works. Thanks!
