### ISSUE TITLE
Allow merger to publish head_block_drift promethus metrics when it is far behind live blocks

### ISSUE THREAD

**Issue by matthewdarwin** [dfuse-io/merger#13]
If merger is merging blocks from 1 year ago, it doesn't publish `head_block_drift` promethus metrics. It only publishes this data when closer to "live". This would be nice to have.

**Comment by matthewdarwin** [comment]
This seems not to be working.  I still see no data.  Blocks are being merged by mindreader... merger is just reading them in as they are created.

This returns nothing:
```curl -s http://localhost:9102 | grep drift```

**Comment by sduchesneau** [comment]
you're describing a different scenario than the original issue (mindreader is merging vs merger is merging old blocks -- there was a case where it wouldn't update the head block drift, now fixed here --).

**Comment by matthewdarwin** [comment]
ok, well multiple issues. ;-)

Here is dfuse drift chart from the time the chain switches from catching up to "live" for the first time.  (the first mindreader caught up)

![image](https://user-images.githubusercontent.com/26171839/159136948-9f92934a-b02a-4b10-8668-01341a2ed089.png)
